- name: Apply VLAN baseline (one-time)
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure VLAN 1234 exists (baseline)
      cisco.ios.ios_config:
        parents: vlan 1234
        lines:
          - name MANAGED_BY_ANSIBLE
        match: exact
        replace: line

